### ISSUE TITLE
GSD physics namelist options

### ISSUE THREAD

**Issue by dustinswales** [NCAR/gmtb-scm#212] opened 2020-11-09 22:59 UTC
@grantfirl 
I think I found an error in ccpp/physical_namelists/input_GSD_v1.nml. 
When using Thompson MP (imp_physics==8) and do_mynnedmf .or. imfdeepcnv == imfdeepcnv_gf, effr_in must be set to true, otherwise in progclduni() will not use the inputparticle sizesi, but rather just set them to default values. 
This doesn't appear to be and issue in the UFS, https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/ccpp_gsd.nml.IN

**Comment by grantfirl** [comment] 2020-11-09 23:05
It's been a while since I looked at this, but IIRC, I think this might be "by design" for the SCM due to an initialization issue. I'll look into it again.

**Comment by climbfuji** [comment] 2020-11-09 23:06
Yes, effr_in must be true for Thompson. This should be set correctly automatically in the UFS.

**Comment by grantfirl** [comment] 2020-11-10 21:23
@climbfuji I am about to go through the SCM suites/namelists and double-check that they follow what is in the UFS regression tests. My process is as follows:

1. Find the primary regression test file in ufs-weather-model/tests/tests that exercises a given suite. 
2. Using the named suite within the regression test, find the corresponding SDF and make sure that the SCM SDF matches (delete the fast_physics and stochastics group - move the phys_tend scheme to the physics group if necessary).
3. Start from the namelist listed in the INPUT_NML variable (copy over to the SCM in the ccpp/physics_namelists directory) and delete everything except gfs_physics_nml and other physics-associated namelists.
4. When namelist variables refer to environment variables, it is set to what is in ufs-weather-model/tests/default_vars.sh unless the regression test file sets the given environment variable to a non-default value.

Bonus: The tracer configuration files associated with each suite in the SCM are constructed by looking at the field table that is copied over according to the FV3_RUN file used in the regression test and any associated namelist/environment variables that are set above. 

This is a manual process; there is no script that does this for me. As such, I do this process in preparation for releases, but typically not more often than that. If there is a change in the suite's namelist settings in FV3, sometimes I catch/apply them during code reviews, but this is not guaranteed.

Having outlined this process, for the GSD suite, I have been keying everything off of the regression test ufs-weather-model/tests/tests/fv3_ccpp_gsd. If this is not correct, and I should be following some other process for this suite, @climbfuji, please let me know.

**Comment by climbfuji** [comment] 2020-11-10 21:31
> @climbfuji I am about to go through the SCM suites/namelists and double-check that they follow what is in the UFS regression tests. My process is as follows:
> 
> 1. Find the primary regression test file in ufs-weather-model/tests/tests that exercises a given suite.
> 2. Using the named suite within the regression test, find the corresponding SDF and make sure that the SCM SDF matches (delete the fast_physics and stochastics group - move the phys_tend scheme to the physics group if necessary).
> 3. Start from the namelist listed in the INPUT_NML variable (copy over to the SCM in the ccpp/physics_namelists directory) and delete everything except gfs_physics_nml and other physics-associated namelists.
> 4. When namelist variables refer to environment variables, it is set to what is in ufs-weather-model/tests/default_vars.sh unless the regression test file sets the given environment variable to a non-default value.
> 
> Bonus: The tracer configuration files associated with each suite in the SCM are constructed by looking at the field table that is copied over according to the FV3_RUN file used in the regression test and any associated namelist/environment variables that are set above.
> 
> This is a manual process; there is no script that does this for me. As such, I do this process in preparation for releases, but typically not more often than that. If there is a change in the suite's namelist settings in FV3, sometimes I catch/apply them during code reviews, but this is not guaranteed.
> 
> Having outlined this process, for the GSD suite, I have been keying everything off of the regression test ufs-weather-model/tests/tests/fv3_ccpp_gsd. If this is not correct, and I should be following some other process for this suite, @climbfuji, please let me know.

Sounds reasonable. The regression test is correct as far as I am concerned.

**Comment by grantfirl** [comment] 2020-11-11 17:58
Addressed in https://github.com/NCAR/gmtb-scm/pull/214

**Closed by grantfirl** 2020-11-11 17:58 UTC
